In [5]:
!python --version

Python 3.11.4


In [12]:
# imports
import torch
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris

In [11]:
torch.__version__

'2.5.0'

In [74]:
iris = load_iris()
data = iris['data']
labels = iris['target']
selected_features = data[:, [1, 3]]

In [75]:
# convert to torch
features_tensor = torch.from_numpy(selected_features).float()
labels_tensor = torch.from_numpy(labels)

In [89]:
# Split
from sklearn.model_selection import train_test_split
train_features, test_features, train_labels, test_labels = train_test_split(
    features_tensor, labels_tensor, test_size=0.2, random_state=42
)


In [90]:
# Build neural network
from torch import nn
network = nn.Sequential(
    nn.Linear(2, 16),  # Input features: 2 (sepal width, petal width)
    nn.ReLU(),
    nn.Linear(16, 3)   # Output logits for 3 classes
)

In [91]:
# Loss and optimizer
from torch import optim
criterion = nn.CrossEntropyLoss()
optim = optim.Adam(network.parameters())

In [100]:
# training
from torch.utils.data import DataLoader, TensorDataset
num_epochs = 1000
batch_size = 32
train_dataset = TensorDataset(train_features,train_labels)
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
for epoch in range(num_epochs):
    for batch in train_loader:
        inputs, labels = batch

        # Zero the gradients
        optim.zero_grad()

        # Forward pass
        outputs = network(inputs)
        loss = criterion(outputs, labels)

        # Backward pass and optimize
        loss.backward()
        optim.step()
    print(f"Epoch [{epoch + 1}/{num_epochs}], Loss: {loss.item():.4f}")

Epoch [1/1000], Loss: 0.0335
Epoch [2/1000], Loss: 0.1592
Epoch [3/1000], Loss: 0.1523
Epoch [4/1000], Loss: 0.0703
Epoch [5/1000], Loss: 0.0161
Epoch [6/1000], Loss: 0.0742
Epoch [7/1000], Loss: 0.0714
Epoch [8/1000], Loss: 0.1752
Epoch [9/1000], Loss: 0.1160
Epoch [10/1000], Loss: 0.0400
Epoch [11/1000], Loss: 0.0366
Epoch [12/1000], Loss: 0.1998
Epoch [13/1000], Loss: 0.1137
Epoch [14/1000], Loss: 0.0681
Epoch [15/1000], Loss: 0.0245
Epoch [16/1000], Loss: 0.1205
Epoch [17/1000], Loss: 0.0904
Epoch [18/1000], Loss: 0.0935
Epoch [19/1000], Loss: 0.1405
Epoch [20/1000], Loss: 0.0213
Epoch [21/1000], Loss: 0.0600
Epoch [22/1000], Loss: 0.1627
Epoch [23/1000], Loss: 0.0300
Epoch [24/1000], Loss: 0.0297
Epoch [25/1000], Loss: 0.1646
Epoch [26/1000], Loss: 0.0182
Epoch [27/1000], Loss: 0.0563
Epoch [28/1000], Loss: 0.1848
Epoch [29/1000], Loss: 0.0498
Epoch [30/1000], Loss: 0.1162
Epoch [31/1000], Loss: 0.1626
Epoch [32/1000], Loss: 0.0255
Epoch [33/1000], Loss: 0.0653
Epoch [34/1000], Lo

In [113]:
# Testing 
batch_size = 32
test_dataset = TensorDataset(test_features,test_labels)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)
for batch in test_loader:
        inputs, labels = batch

        # No gradients
        with torch.no_grad():

        # Forward pass
            outputs = network(inputs)
        print(outputs)

tensor([[-5.7565e+00,  4.4281e+00, -1.6786e+00],
        [ 1.4295e+01, -2.6080e+00, -1.6801e+01],
        [-1.8550e+01, -6.7196e-01,  1.0437e+01],
        [-8.9859e+00,  3.2594e+00,  1.2341e+00],
        [-8.0612e+00,  3.5059e+00,  5.0334e-01],
        [ 1.1428e+01, -9.4525e-01, -1.4430e+01],
        [-6.6812e+00,  4.1816e+00, -9.4791e-01],
        [-1.7749e+01, -1.6630e-04,  9.2415e+00],
        [-1.0579e+01,  1.7572e+00,  3.7559e+00],
        [-5.9841e+00,  4.2135e+00, -1.3184e+00],
        [-1.4065e+01,  1.5977e+00,  5.6083e+00],
        [ 1.2839e+01, -2.2380e+00, -1.5116e+01],
        [ 1.3979e+01, -2.6597e+00, -1.6333e+01],
        [ 1.3251e+01, -2.4748e+00, -1.5490e+01],
        [ 1.4295e+01, -2.6080e+00, -1.6801e+01],
        [-9.2279e+00,  3.6567e+00,  8.8405e-01],
        [-1.6825e+01,  2.4633e-01,  8.5108e+00],
        [-5.2869e+00,  4.2454e+00, -1.6889e+00],
        [-6.9088e+00,  3.9670e+00, -5.8765e-01],
        [-1.7280e+01, -1.8287e-01,  9.2313e+00],
        [ 1.2743e+01

In [114]:
# Evaluation
predicted_classes = torch.argmax(outputs, dim=1)
predicted_classes

tensor([1, 0, 2, 1, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2, 0, 2,
        2, 2, 2, 2, 0, 0])

In [116]:
predicted_classes

tensor([1, 0, 2, 1, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2, 0, 2,
        2, 2, 2, 2, 0, 0])

In [117]:
test_labels

tensor([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2, 0, 2,
        2, 2, 2, 2, 0, 0])

In [115]:
correct = (predicted_classes == test_labels).sum().item()
accuracy = correct / test_labels.size(0)
accuracy

0.9666666666666667